name: Schedule job - Ping Jenkins each 20 min

on:
  schedule:
    - cron:  '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      HEROKU_APP_URL: https://jenkins-dyno.herokuapp.com/

    steps:
      - uses: actions/checkout@v2

      - name: Ping Jenkins
        run: |
          curl ${{ env.HEROKU_APP_URL }}